/**
 * Seed data standing in for the certificates and spreadsheets MOS's own problem
 * summary names as the actual blocker: "Commissioning date, warranty status,
 * service certificates, previous calls on the house. The homeowner knows none of
 * it, and our system does not hold it either."
 *
 * Nine sites, each set up to exercise one documented rule path (see
 * server/triage.js and docs/PRD.md §7):
 *   1. Aidan Byrne      — heat pump, H-code, within MOS's 1-year warranty
 *   2. Maura Kelly       — no hot water, past MOS warranty, no builder warranty left
 *   3. Sean & Orla Whelan — no heating, past MOS warranty, within builder's warranty
 *   4. Fiona Doyle       — leak matching the builder/snagging checklist
 *   5. Tomás Nolan       — other query / advice (guidance only)
 *   6. Grainne Lynch     — missing commissioning date
 *   7. Padraig Costello  — heat pump, F-code, service certs not yet supplied
 *   8. Roisín Fallon     — heat pump, F-code, service certs supplied (Heat Merchants)
 *   9. Cian Murphy       — leak (genuine plumbing), past MOS and builder warranty
 */

const SITES = [
  {
    siteId: 'site-1001',
    customerName: 'Aidan Byrne',
    phone: '087 555 0101',
    email: 'aidan.byrne@example.ie',
    address: '14 Maynooth Road, Kilcock, Co. Kildare',
    eircode: 'W23 K1F2',
    builderName: 'Rivermount Developments',
    builderWarrantyMonths: null,
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Panasonic',
    modelNumber: 'Aquarea T-CAP 8kW',
    serialNumber: 'PA-88213',
    commissioningDate: '2026-07-01',
    mosWarrantyMonths: 12,
    notes: 'Recently commissioned; still inside MOS\'s 1-year plumbing warranty.',
  },
  {
    siteId: 'site-1002',
    customerName: 'Maura Kelly',
    phone: '086 555 0102',
    email: 'maura.kelly@example.ie',
    address: '2 Church View, Enfield, Co. Meath',
    eircode: 'A83 F4H1',
    builderName: 'Oakfield Homes',
    builderWarrantyMonths: 12,
    systemType: 'Gas Boiler',
    manufacturer: 'Worcester Bosch',
    modelNumber: 'Greenstar 8000',
    serialNumber: 'WB-40217',
    commissioningDate: '2022-03-05',
    mosWarrantyMonths: 12,
    notes: 'Oakfield\'s own builder warranty matched MOS\'s 1 year and has also expired.',
  },
  {
    siteId: 'site-1003',
    customerName: 'Sean & Orla Whelan',
    phone: '085 555 0103',
    email: 'whelan.family@example.ie',
    address: '9 Riverside Drive, Trim, Co. Meath',
    eircode: 'C15 Y2W3',
    builderName: 'Kildare Meadows Ltd',
    builderWarrantyMonths: 24,
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Mitsubishi Ecodan',
    modelNumber: 'Ecodan 11kW',
    serialNumber: 'MI-71029',
    commissioningDate: '2024-11-28',
    mosWarrantyMonths: 12,
    notes: 'Past MOS\'s 1-year warranty, but Kildare Meadows gives a 2-year builder warranty on top.',
  },
  {
    siteId: 'site-1004',
    customerName: 'Fiona Doyle',
    phone: '083 555 0104',
    email: 'fiona.doyle@example.ie',
    address: '31 Millbrook Lawns, Maynooth, Co. Kildare',
    eircode: 'W23 P8D5',
    builderName: 'Rivermount Developments',
    builderWarrantyMonths: null,
    systemType: 'Gas Boiler',
    manufacturer: 'Vaillant',
    modelNumber: 'ecoTEC plus 832',
    serialNumber: 'VL-55810',
    commissioningDate: '2026-06-16',
    mosWarrantyMonths: 12,
    notes: 'Still within MOS\'s warranty window, but the fault reported is a shower tray seal — a builder/snagging item regardless.',
  },
  {
    siteId: 'site-1005',
    customerName: 'Tomás Nolan',
    phone: '087 555 0105',
    email: 'tomas.nolan@example.ie',
    address: '6 Abbey Court, Kilcock, Co. Kildare',
    eircode: 'W23 T9L4',
    builderName: 'Rivermount Developments',
    builderWarrantyMonths: null,
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Panasonic',
    modelNumber: 'Aquarea T-CAP 10kW',
    serialNumber: 'PA-19934',
    commissioningDate: '2026-08-28',
    mosWarrantyMonths: 12,
    notes: 'Commissioned two weeks ago; asking how to use the heat pump controls.',
  },
  {
    siteId: 'site-1006',
    customerName: 'Grainne Lynch',
    phone: '089 555 0106',
    email: 'grainne.lynch@example.ie',
    address: '18 The Paddocks, Clane, Co. Kildare',
    eircode: 'W91 R3C6',
    builderName: 'Oakfield Homes',
    builderWarrantyMonths: 12,
    systemType: 'Gas Boiler',
    manufacturer: 'Worcester Bosch',
    modelNumber: 'Greenstar 8000',
    serialNumber: 'WB-30281',
    // Deliberately missing — models the exact gap MOS's problem summary describes:
    // commissioning data "sits in certificates and spreadsheets", not the system.
    commissioningDate: null,
    mosWarrantyMonths: 12,
    notes: 'Commissioning certificate was never logged against this house — warranty status unknown.',
  },
  {
    siteId: 'site-1007',
    customerName: 'Padraig Costello',
    phone: '085 555 0107',
    email: 'p.costello@example.ie',
    address: '4 Hillcrest, Celbridge, Co. Kildare',
    eircode: 'W23 X4V7',
    builderName: 'Kildare Meadows Ltd',
    builderWarrantyMonths: 24,
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Panasonic',
    modelNumber: 'Aquarea T-CAP 11kW',
    serialNumber: 'PA-90144',
    commissioningDate: '2024-02-09',
    mosWarrantyMonths: 12,
    notes: 'Two prior aftercare calls logged against this house — a repeat-fault candidate.',
  },
  {
    siteId: 'site-1008',
    customerName: 'Roisín Fallon',
    phone: '086 555 0108',
    email: 'roisin.fallon@example.ie',
    address: '22 The Meadows, Celbridge, Co. Kildare',
    eircode: 'W23 M2N8',
    builderName: 'Kildare Meadows Ltd',
    builderWarrantyMonths: 24,
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Panasonic',
    modelNumber: 'Aquarea T-CAP 8kW',
    serialNumber: 'PA-60512',
    commissioningDate: '2023-09-01',
    mosWarrantyMonths: 12,
    notes: 'Keeps an up-to-date annual service certificate on file with the homeowner.',
  },
  {
    siteId: 'site-1009',
    customerName: 'Cian Murphy',
    phone: '089 555 0109',
    email: 'cian.murphy@example.ie',
    address: '10 Riverside Drive, Trim, Co. Meath',
    eircode: 'C15 Y2W9',
    builderName: 'Oakfield Homes',
    builderWarrantyMonths: 12,
    systemType: 'Gas Boiler',
    manufacturer: 'Worcester Bosch',
    modelNumber: 'Greenstar 8000',
    serialNumber: 'WB-70933',
    commissioningDate: '2023-01-10',
    mosWarrantyMonths: 12,
    notes: 'Past both MOS\'s and Oakfield\'s warranty windows.',
  },
];

// A handful of tickets already in flight, so the queue isn't empty on first load,
// and so Padraig Costello's site already shows a repeat-call history.
const TICKETS = [
  {
    ticketId: 'ticket-9001',
    siteId: 'site-1007',
    channel: 'phone',
    reportedBy: 'Padraig Costello',
    builderIfKnown: 'Kildare Meadows Ltd',
    faultTypeId: 'HEAT-PUMP-FAULT',
    errorCode: 'H90',
    serialNumber: 'PA-90144',
    photos: ['display-photo-1.jpg'],
    symptoms: 'Heat pump stopped, controller showing H90.',
    leakChecklist: {},
    serviceCertsProvided: false,
    openedAt: '2026-07-30T09:12:00.000Z',
    state: 'Resolved',
  },
  {
    ticketId: 'ticket-9002',
    siteId: 'site-1002',
    channel: 'web-form',
    reportedBy: 'Maura Kelly',
    builderIfKnown: 'Oakfield Homes',
    faultTypeId: 'NO-HOT-WATER',
    errorCode: '',
    serialNumber: '',
    photos: ['controller-photo-1.jpg'],
    symptoms: 'No hot water since this morning, radiators cold too.',
    leakChecklist: {},
    serviceCertsProvided: false,
    openedAt: '2026-09-10T07:40:00.000Z',
    state: 'Scheduled',
  },
];

module.exports = { SITES, TICKETS };
