/**
 * Seed data standing in for the spreadsheets this project replaces: the house/asset
 * register (address, system, install & commissioning dates, warranty terms, service
 * contract status) that today lives outside the ticketing system.
 */

function addMonths(dateStr, months) {
  const d = new Date(dateStr);
  d.setMonth(d.getMonth() + months);
  return d.toISOString().slice(0, 10);
}

const SITES = [
  {
    siteId: 'site-1001',
    customerName: 'Aidan Byrne',
    phone: '087 555 0101',
    email: 'aidan.byrne@example.ie',
    address: '14 Maynooth Road, Kilcock, Co. Kildare',
    eircode: 'W23 K1F2',
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Daikin',
    modelNumber: 'Altherma 3 8kW',
    serialNumber: 'DK-88213',
    installedBy: 'MOS Mechanical',
    installDate: '2025-08-10',
    commissioningDate: '2025-08-18',
    warrantyPartsMonths: 84,
    warrantyLabourMonths: 24,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: true,
    lastServiceDate: null,
    vulnerableOccupant: false,
    notes: 'SEAI deep retrofit, heat pump installed under Home Comfort Retrofits.',
  },
  {
    siteId: 'site-1002',
    customerName: 'Maura Kelly',
    phone: '086 555 0102',
    email: 'maura.kelly@example.ie',
    address: '2 Church View, Enfield, Co. Meath',
    eircode: 'A83 F4H1',
    systemType: 'Gas Boiler',
    manufacturer: 'Worcester Bosch',
    modelNumber: 'Greenstar 8000',
    serialNumber: 'WB-40217',
    installedBy: 'MOS Mechanical',
    installDate: '2022-03-02',
    commissioningDate: '2022-03-05',
    warrantyPartsMonths: 60,
    warrantyLabourMonths: 12,
    serviceContract: { active: true, plan: 'Annual Care Plan', expiresAt: '2027-03-05' },
    seaiGrantScheme: false,
    lastServiceDate: '2026-03-01',
    vulnerableOccupant: true,
    notes: 'Elderly occupant living alone — flagged for priority handling on no-heat calls.',
  },
  {
    siteId: 'site-1003',
    customerName: 'Sean & Orla Whelan',
    phone: '085 555 0103',
    email: 'whelan.family@example.ie',
    address: '9 Riverside Drive, Trim, Co. Meath',
    eircode: 'C15 Y2W3',
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Mitsubishi Ecodan',
    modelNumber: 'Ecodan 11kW',
    serialNumber: 'MI-71029',
    installedBy: 'MOS Mechanical',
    installDate: '2021-11-20',
    commissioningDate: '2021-11-28',
    warrantyPartsMonths: 60,
    warrantyLabourMonths: 24,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: true,
    lastServiceDate: '2024-11-15',
    vulnerableOccupant: false,
    notes: 'Warranty (parts + labour) has lapsed; no service contract taken up.',
  },
  {
    siteId: 'site-1004',
    customerName: 'Fiona Doyle',
    phone: '083 555 0104',
    email: 'fiona.doyle@example.ie',
    address: '31 Millbrook Lawns, Maynooth, Co. Kildare',
    eircode: 'W23 P8D5',
    systemType: 'Gas Boiler',
    manufacturer: 'Vaillant',
    modelNumber: 'ecoTEC plus 832',
    serialNumber: 'VL-55810',
    installedBy: 'Kildare Heating Supplies Ltd',
    installDate: '2023-06-14',
    commissioningDate: '2023-06-16',
    warrantyPartsMonths: 60,
    warrantyLabourMonths: 12,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: false,
    lastServiceDate: null,
    vulnerableOccupant: false,
    notes: 'Installed by a third party before the homeowner became an MOS aftercare customer.',
  },
  {
    siteId: 'site-1005',
    customerName: 'Tomás Nolan',
    phone: '087 555 0105',
    email: 'tomas.nolan@example.ie',
    address: '6 Abbey Court, Kilcock, Co. Kildare',
    eircode: 'W23 T9L4',
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Grant',
    modelNumber: 'Aerona3 10kW',
    serialNumber: 'GR-19934',
    installedBy: 'MOS Mechanical',
    installDate: '2026-08-20',
    commissioningDate: '2026-08-28',
    warrantyPartsMonths: 84,
    warrantyLabourMonths: 24,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: true,
    lastServiceDate: null,
    vulnerableOccupant: false,
    notes: 'Commissioned two weeks ago — still inside the 30-day post-install snag window.',
  },
  {
    siteId: 'site-1006',
    customerName: 'Grainne Lynch',
    phone: '089 555 0106',
    email: 'grainne.lynch@example.ie',
    address: '18 The Paddocks, Clane, Co. Kildare',
    eircode: 'W91 R3C6',
    systemType: 'MVHR',
    manufacturer: 'Vent-Axia',
    modelNumber: 'Sentinel Kinetic Advance',
    serialNumber: 'VA-30281',
    installedBy: 'MOS Mechanical',
    // Deliberately missing — models the exact data gap the project is meant to close.
    installDate: '2024-01-15',
    commissioningDate: null,
    warrantyPartsMonths: 24,
    warrantyLabourMonths: 12,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: false,
    lastServiceDate: null,
    vulnerableOccupant: false,
    notes: 'Commissioning certificate was never logged in the register — warranty status unknown.',
  },
  {
    siteId: 'site-1007',
    customerName: 'Padraig Costello',
    phone: '085 555 0107',
    email: 'p.costello@example.ie',
    address: '4 Hillcrest, Celbridge, Co. Kildare',
    eircode: 'W23 X4V7',
    systemType: 'Air-to-Water Heat Pump',
    manufacturer: 'Daikin',
    modelNumber: 'Altherma 3 11kW',
    serialNumber: 'DK-90144',
    installedBy: 'MOS Mechanical',
    installDate: '2024-02-01',
    commissioningDate: '2024-02-09',
    warrantyPartsMonths: 84,
    warrantyLabourMonths: 24,
    serviceContract: { active: false, plan: null, expiresAt: null },
    seaiGrantScheme: true,
    lastServiceDate: '2025-02-01',
    vulnerableOccupant: false,
    notes: 'Two aftercare visits in the last 90 days for the same fault code — candidate for pattern review.',
  },
];

// A handful of tickets already in flight, so the queue isn't empty on first load.
const TICKETS = [
  {
    ticketId: 'ticket-9001',
    siteId: 'site-1007',
    channel: 'phone',
    reportedBy: 'Padraig Costello',
    faultTypeId: 'HP-FAULT',
    errorCode: 'E7',
    photos: [],
    symptoms: 'Heat pump stopped and outdoor unit showing flashing red light.',
    gasSmell: false,
    coAlarm: false,
    openedAt: '2026-08-30T09:12:00.000Z',
    state: 'Resolved',
  },
  {
    ticketId: 'ticket-9002',
    siteId: 'site-1002',
    channel: 'web-form',
    reportedBy: 'Maura Kelly',
    faultTypeId: 'HEAT-NONE',
    errorCode: '',
    photos: [],
    symptoms: 'No hot water since this morning, radiators cold.',
    gasSmell: false,
    coAlarm: false,
    openedAt: '2026-09-10T07:40:00.000Z',
    state: 'Scheduled',
  },
];

module.exports = { SITES, TICKETS, addMonths };
